libcudart.so.12!tag_array::probe(const tag_array * const this, new_addr_type addr, unsigned int & idx, mem_access_sector_mask_t mask, bool is_write, unsigned long long time, bool probe_mode, mem_fetch * mf) (\home\kuanbba\dev\accel-sim\accel-sim-framework\gpu-simulator\gpgpu-sim\src\gpgpu-sim\gpu-cache.cc:291)
libcudart.so.12!tag_array::probe(const tag_array * const this, new_addr_type addr, unsigned int & idx, mem_fetch * mf, bool is_write, unsigned long long time, bool probe_mode) (\home\kuanbba\dev\accel-sim\accel-sim-framework\gpu-simulator\gpgpu-sim\src\gpgpu-sim\gpu-cache.cc:246)
libcudart.so.12!data_cache::access(data_cache * const this, new_addr_type addr, mem_fetch * mf, unsigned long long time, std::__cxx11::list<cache_event, std::allocator<cache_event> > & events) (\home\kuanbba\dev\accel-sim\accel-sim-framework\gpu-simulator\gpgpu-sim\src\gpgpu-sim\gpu-cache.cc:2001)
libcudart.so.12!l1_cache::access(l1_cache * const this, new_addr_type addr, mem_fetch * mf, unsigned long long time, std::__cxx11::list<cache_event, std::allocator<cache_event> > & events) (\home\kuanbba\dev\accel-sim\accel-sim-framework\gpu-simulator\gpgpu-sim\src\gpgpu-sim\gpu-cache.cc:2050)
libcudart.so.12!ldst_unit::L1_latency_queue_cycle(ldst_unit * const this) (\home\kuanbba\dev\accel-sim\accel-sim-framework\gpu-simulator\gpgpu-sim\src\gpgpu-sim\shader.cc:2356)
libcudart.so.12!ldst_unit::cycle(ldst_unit * const this) (\home\kuanbba\dev\accel-sim\accel-sim-framework\gpu-simulator\gpgpu-sim\src\gpgpu-sim\shader.cc:3230)
libcudart.so.12!shader_core_ctx::execute(shader_core_ctx * const this) (\home\kuanbba\dev\accel-sim\accel-sim-framework\gpu-simulator\gpgpu-sim\src\gpgpu-sim\shader.cc:1976)
libcudart.so.12!shader_core_ctx::cycle(shader_core_ctx * const this) (\home\kuanbba\dev\accel-sim\accel-sim-framework\gpu-simulator\gpgpu-sim\src\gpgpu-sim\shader.cc:4009)
libcudart.so.12!simt_core_cluster::core_cycle(simt_core_cluster * const this) (\home\kuanbba\dev\accel-sim\accel-sim-framework\gpu-simulator\gpgpu-sim\src\gpgpu-sim\shader.cc:4820)
libcudart.so.12!gpgpu_sim::cycle(gpgpu_sim * const this) (\home\kuanbba\dev\accel-sim\accel-sim-framework\gpu-simulator\gpgpu-sim\src\gpgpu-sim\gpu-sim.cc:2080)
libcudart.so.12!gpgpu_sim_thread_concurrent(void * ctx_ptr) (\home\kuanbba\dev\accel-sim\accel-sim-framework\gpu-simulator\gpgpu-sim\src\gpgpusim_entrypoint.cc:146)
libpthread.so.0!start_thread(void * arg) (\build\glibc-B3wQXB\glibc-2.31\nptl\pthread_create.c:477)
libc.so.6!clone() (\build\glibc-B3wQXB\glibc-2.31\sysdeps\unix\sysv\linux\x86_64\clone.S:95)

libcudart.so.12!tag_array::probe(const tag_array * const this, new_addr_type addr, unsigned int & idx, mem_access_sector_mask_t mask, bool is_write, unsigned long long time, bool probe_mode, mem_fetch * mf) (\home\kuanbba\dev\accel-sim\accel-sim-framework\gpu-simulator\gpgpu-sim\src\gpgpu-sim\gpu-cache.cc:291)
libcudart.so.12!tag_array::probe(const tag_array * const this, new_addr_type addr, unsigned int & idx, mem_fetch * mf, bool is_write, unsigned long long time, bool probe_mode) (\home\kuanbba\dev\accel-sim\accel-sim-framework\gpu-simulator\gpgpu-sim\src\gpgpu-sim\gpu-cache.cc:246)
libcudart.so.12!tag_array::access(tag_array * const this, new_addr_type addr, unsigned int time, unsigned int & idx, bool & wb, evicted_block_info & evicted, mem_fetch * mf) (\home\kuanbba\dev\accel-sim\accel-sim-framework\gpu-simulator\gpgpu-sim\src\gpgpu-sim\gpu-cache.cc:366)
libcudart.so.12!data_cache::wr_miss_wa_lazy_fetch_on_read(data_cache * const this, new_addr_type addr, unsigned int cache_index, mem_fetch * mf, unsigned int time, std::__cxx11::list<cache_event, std::allocator<cache_event> > & events, cache_request_status status) (\home\kuanbba\dev\accel-sim\accel-sim-framework\gpu-simulator\gpgpu-sim\src\gpgpu-sim\gpu-cache.cc:1769)
libcudart.so.12!data_cache::process_tag_probe(data_cache * const this, bool wr, cache_request_status probe_status, new_addr_type addr, unsigned int cache_index, mem_fetch * mf, unsigned int time, std::__cxx11::list<cache_event, std::allocator<cache_event> > & events) (\home\kuanbba\dev\accel-sim\accel-sim-framework\gpu-simulator\gpgpu-sim\src\gpgpu-sim\gpu-cache.cc:1961)
libcudart.so.12!data_cache::access(data_cache * const this, new_addr_type addr, mem_fetch * mf, unsigned long long time, std::__cxx11::list<cache_event, std::allocator<cache_event> > & events) (\home\kuanbba\dev\accel-sim\accel-sim-framework\gpu-simulator\gpgpu-sim\src\gpgpu-sim\gpu-cache.cc:2003)
libcudart.so.12!l1_cache::access(l1_cache * const this, new_addr_type addr, mem_fetch * mf, unsigned long long time, std::__cxx11::list<cache_event, std::allocator<cache_event> > & events) (\home\kuanbba\dev\accel-sim\accel-sim-framework\gpu-simulator\gpgpu-sim\src\gpgpu-sim\gpu-cache.cc:2050)
libcudart.so.12!ldst_unit::L1_latency_queue_cycle(ldst_unit * const this) (\home\kuanbba\dev\accel-sim\accel-sim-framework\gpu-simulator\gpgpu-sim\src\gpgpu-sim\shader.cc:2356)
libcudart.so.12!ldst_unit::cycle(ldst_unit * const this) (\home\kuanbba\dev\accel-sim\accel-sim-framework\gpu-simulator\gpgpu-sim\src\gpgpu-sim\shader.cc:3230)
libcudart.so.12!shader_core_ctx::execute(shader_core_ctx * const this) (\home\kuanbba\dev\accel-sim\accel-sim-framework\gpu-simulator\gpgpu-sim\src\gpgpu-sim\shader.cc:1976)
libcudart.so.12!shader_core_ctx::cycle(shader_core_ctx * const this) (\home\kuanbba\dev\accel-sim\accel-sim-framework\gpu-simulator\gpgpu-sim\src\gpgpu-sim\shader.cc:4009)
libcudart.so.12!simt_core_cluster::core_cycle(simt_core_cluster * const this) (\home\kuanbba\dev\accel-sim\accel-sim-framework\gpu-simulator\gpgpu-sim\src\gpgpu-sim\shader.cc:4820)
libcudart.so.12!gpgpu_sim::cycle(gpgpu_sim * const this) (\home\kuanbba\dev\accel-sim\accel-sim-framework\gpu-simulator\gpgpu-sim\src\gpgpu-sim\gpu-sim.cc:2080)
libcudart.so.12!gpgpu_sim_thread_concurrent(void * ctx_ptr) (\home\kuanbba\dev\accel-sim\accel-sim-framework\gpu-simulator\gpgpu-sim\src\gpgpusim_entrypoint.cc:146)
libpthread.so.0!start_thread(void * arg) (\build\glibc-B3wQXB\glibc-2.31\nptl\pthread_create.c:477)
libc.so.6!clone() (\build\glibc-B3wQXB\glibc-2.31\sysdeps\unix\sysv\linux\x86_64\clone.S:95)

// 初始化的Seg Fault
libcudart.so!gpgpu_sim::active(gpgpu_sim * const this) (\home\kuanbba\dev\accel-sim\accel-sim-framework\gpu-simulator\gpgpu-sim\src\gpgpu-sim\gpu-sim.cc:1158)
<function called from gdb> (Unknown Source:0)
libpthread.so.0!__GI___pthread_mutex_lock(pthread_mutex_t * mutex) (\build\glibc-B3wQXB\glibc-2.31\nptl\pthread_mutex_lock.c:67)
libcudart.so!stream_manager::empty_protected(stream_manager * const this) (\home\kuanbba\dev\accel-sim\accel-sim-framework\gpu-simulator\gpgpu-sim\src\stream_manager.cc:466)
<function called from gdb> (Unknown Source:0)
libcudart.so!gpgpu_t::gpgpu_t(gpgpu_t * const this, const gpgpu_functional_sim_config & config, gpgpu_context * ctx) (\home\kuanbba\dev\accel-sim\accel-sim-framework\gpu-simulator\gpgpu-sim\src\abstract_hardware_model.cc:187)
libcudart.so!gpgpu_sim::gpgpu_sim(gpgpu_sim * const this, const gpgpu_sim_config & config, gpgpu_context * ctx) (\home\kuanbba\dev\accel-sim\accel-sim-framework\gpu-simulator\gpgpu-sim\src\gpgpu-sim\gpu-sim.cc:987)
trace_gpgpu_sim::trace_gpgpu_sim(trace_gpgpu_sim * const this, const gpgpu_sim_config & config, gpgpu_context * ctx) (\home\kuanbba\dev\accel-sim\accel-sim-framework\gpu-simulator\trace-driven\trace_driven.h:173)
accel_sim_framework::gpgpu_trace_sim_init_perf_model(accel_sim_framework * const this, int argc, const char ** argv, gpgpu_context * m_gpgpu_context, trace_config * m_config) (\home\kuanbba\dev\accel-sim\accel-sim-framework\gpu-simulator\accel-sim.cc:231)
accel_sim_framework::accel_sim_framework(accel_sim_framework * const this, int argc, const char ** argv) (\home\kuanbba\dev\accel-sim\accel-sim-framework\gpu-simulator\accel-sim.cc:30)
main(int argc, const char ** argv) (\home\kuanbba\dev\accel-sim\accel-sim-framework\gpu-simulator\main.cc:29)


libcudart.so!gpgpu_sim::active(gpgpu_sim * const this) (\home\kuanbba\dev\accel-sim\accel-sim-framework\gpu-simulator\gpgpu-sim\src\gpgpu-sim\gpu-sim.cc:1158)
<function called from gdb> (Unknown Source:0)
libpthread.so.0!__GI___pthread_mutex_lock(pthread_mutex_t * mutex) (\build\glibc-B3wQXB\glibc-2.31\nptl\pthread_mutex_lock.c:67)
libcudart.so!stream_manager::empty_protected(stream_manager * const this) (\home\kuanbba\dev\accel-sim\accel-sim-framework\gpu-simulator\gpgpu-sim\src\stream_manager.cc:466)
<function called from gdb> (Unknown Source:0)
libcudart.so!gpgpu_sim::gpgpu_sim(gpgpu_sim * const this, const gpgpu_sim_config & config, gpgpu_context * ctx) (\home\kuanbba\dev\accel-sim\accel-sim-framework\gpu-simulator\gpgpu-sim\src\gpgpu-sim\gpu-sim.cc:988)
trace_gpgpu_sim::trace_gpgpu_sim(trace_gpgpu_sim * const this, const gpgpu_sim_config & config, gpgpu_context * ctx) (\home\kuanbba\dev\accel-sim\accel-sim-framework\gpu-simulator\trace-driven\trace_driven.h:173)
accel_sim_framework::gpgpu_trace_sim_init_perf_model(accel_sim_framework * const this, int argc, const char ** argv, gpgpu_context * m_gpgpu_context, trace_config * m_config) (\home\kuanbba\dev\accel-sim\accel-sim-framework\gpu-simulator\accel-sim.cc:231)
accel_sim_framework::accel_sim_framework(accel_sim_framework * const this, int argc, const char ** argv) (\home\kuanbba\dev\accel-sim\accel-sim-framework\gpu-simulator\accel-sim.cc:30)
main(int argc, const char ** argv) (\home\kuanbba\dev\accel-sim\accel-sim-framework\gpu-simulator\main.cc:29)

给输出stats赋值的链路
libcudart.so!cache_stats::inc_stats(cache_stats * const this, int access_type, int access_outcome, unsigned long long streamID) (\home\kuanbba\dev\accel-sim\accel-sim-framework\gpu-simulator\gpgpu-sim\src\gpgpu-sim\gpu-cache.cc:800)
libcudart.so!data_cache::access(data_cache * const this, new_addr_type addr, mem_fetch * mf, unsigned long long time, std::__cxx11::list<cache_event, std::allocator<cache_event> > & events) (\home\kuanbba\dev\accel-sim\accel-sim-framework\gpu-simulator\gpgpu-sim\src\gpgpu-sim\gpu-cache.cc:2185)
libcudart.so!l1_cache::access(l1_cache * const this, new_addr_type addr, mem_fetch * mf, unsigned long long time, std::__cxx11::list<cache_event, std::allocator<cache_event> > & events) (\home\kuanbba\dev\accel-sim\accel-sim-framework\gpu-simulator\gpgpu-sim\src\gpgpu-sim\gpu-cache.cc:2236)
libcudart.so!ldst_unit::L1_latency_queue_cycle(ldst_unit * const this) (\home\kuanbba\dev\accel-sim\accel-sim-framework\gpu-simulator\gpgpu-sim\src\gpgpu-sim\shader.cc:2425)
libcudart.so!ldst_unit::cycle(ldst_unit * const this) (\home\kuanbba\dev\accel-sim\accel-sim-framework\gpu-simulator\gpgpu-sim\src\gpgpu-sim\shader.cc:3377)
libcudart.so!shader_core_ctx::execute(shader_core_ctx * const this) (\home\kuanbba\dev\accel-sim\accel-sim-framework\gpu-simulator\gpgpu-sim\src\gpgpu-sim\shader.cc:2016)
libcudart.so!shader_core_ctx::cycle(shader_core_ctx * const this) (\home\kuanbba\dev\accel-sim\accel-sim-framework\gpu-simulator\gpgpu-sim\src\gpgpu-sim\shader.cc:4189)
libcudart.so!simt_core_cluster::core_cycle(simt_core_cluster * const this) (\home\kuanbba\dev\accel-sim\accel-sim-framework\gpu-simulator\gpgpu-sim\src\gpgpu-sim\shader.cc:5000)
libcudart.so!gpgpu_sim::cycle(gpgpu_sim * const this) (\home\kuanbba\dev\accel-sim\accel-sim-framework\gpu-simulator\gpgpu-sim\src\gpgpu-sim\gpu-sim.cc:2141)
accel_sim_framework::simulate(accel_sim_framework * const this) (\home\kuanbba\dev\accel-sim\accel-sim-framework\gpu-simulator\accel-sim.cc:160)
accel_sim_framework::simulation_loop(accel_sim_framework * const this) (\home\kuanbba\dev\accel-sim\accel-sim-framework\gpu-simulator\accel-sim.cc:75)
main(int argc, const char ** argv) (\home\kuanbba\dev\accel-sim\accel-sim-framework\gpu-simulator\main.cc:30)

对L1D进行初始化配置的链路(包括m_miss_queue_size)
cache_config::init(cache_config * const this, char * config, FuncCache status) (\home\kuanbba\dev\accel-sim\accel-sim-framework\gpu-simulator\gpgpu-sim\src\gpgpu-sim\gpu-cache.h:607)
l1d_cache_config::init(l1d_cache_config * const this, char * config, FuncCache status) (\home\kuanbba\dev\accel-sim\accel-sim-framework\gpu-simulator\gpgpu-sim\src\gpgpu-sim\gpu-cache.h:975)
shader_core_config::init(shader_core_config * const this) (\home\kuanbba\dev\accel-sim\accel-sim-framework\gpu-simulator\gpgpu-sim\src\gpgpu-sim\shader.h:1582)
gpgpu_sim_config::init(gpgpu_sim_config * const this) (\home\kuanbba\dev\accel-sim\accel-sim-framework\gpu-simulator\gpgpu-sim\src\gpgpu-sim\gpu-sim.h:423)
accel_sim_framework::gpgpu_trace_sim_init_perf_model(accel_sim_framework * const this, int argc, const char ** argv, gpgpu_context * m_gpgpu_context, trace_config * m_config) (\home\kuanbba\dev\accel-sim\accel-sim-framework\gpu-simulator\accel-sim.cc:226)
accel_sim_framework::accel_sim_framework(accel_sim_framework * const this, int argc, const char ** argv) (\home\kuanbba\dev\accel-sim\accel-sim-framework\gpu-simulator\accel-sim.cc:29)
main(int argc, const char ** argv) (\home\kuanbba\dev\accel-sim\accel-sim-framework\gpu-simulator\main.cc:29)

